/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as Create_withAIRouteImport } from './routes/create_withAI'
import { Route as Create_withManualRouteImport } from './routes/create_withManual'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as Explore_nearby_allRouteImport } from './routes/explore_nearby_all'
import { Route as Explore_recommend_allRouteImport } from './routes/explore_recommend_all'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PersonalSurveyRouteImport } from './routes/personal-survey'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as AdminTest_AlgorithmRouteImport } from './routes/admin/Test_Algorithm'
import { Route as AdminMapRouteImport } from './routes/admin/map'
import { Route as AdminPlaceImagesRouteImport } from './routes/admin/place-images'
import { Route as AdminRating_attractionRouteImport } from './routes/admin/rating_attraction'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as Trips_detailTripIdRouteImport } from './routes/trips_detail.$tripId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const Create_withAIRoute = Create_withAIRouteImport.update({
  id: '/create_withAI',
  path: '/create_withAI',
  getParentRoute: () => rootRouteImport,
} as any)
const Create_withManualRoute = Create_withManualRouteImport.update({
  id: '/create_withManual',
  path: '/create_withManual',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const Explore_nearby_allRoute = Explore_nearby_allRouteImport.update({
  id: '/explore_nearby_all',
  path: '/explore_nearby_all',
  getParentRoute: () => rootRouteImport,
} as any)
const Explore_recommend_allRoute = Explore_recommend_allRouteImport.update({
  id: '/explore_recommend_all',
  path: '/explore_recommend_all',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalSurveyRoute = PersonalSurveyRouteImport.update({
  id: '/personal-survey',
  path: '/personal-survey',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTest_AlgorithmRoute = AdminTest_AlgorithmRouteImport.update({
  id: '/admin/Test_Algorithm',
  path: '/admin/Test_Algorithm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/admin/map',
  path: '/admin/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlaceImagesRoute = AdminPlaceImagesRouteImport.update({
  id: '/admin/place-images',
  path: '/admin/place-images',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRating_attractionRoute = AdminRating_attractionRouteImport.update({
  id: '/admin/rating_attraction',
  path: '/admin/rating_attraction',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const Trips_detailTripIdRoute = Trips_detailTripIdRouteImport.update({
  id: '/trips_detail/$tripId',
  path: '/trips_detail/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/create_withAI': typeof Create_withAIRoute
  '/create_withManual': typeof Create_withManualRoute
  '/explore': typeof ExploreRoute
  '/explore_nearby_all': typeof Explore_nearby_allRoute
  '/explore_recommend_all': typeof Explore_recommend_allRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/personal-survey': typeof PersonalSurveyRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/trips': typeof TripsRoute
  '/admin/Test_Algorithm': typeof AdminTest_AlgorithmRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/place-images': typeof AdminPlaceImagesRoute
  '/admin/rating_attraction': typeof AdminRating_attractionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/trips_detail/$tripId': typeof Trips_detailTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/create_withAI': typeof Create_withAIRoute
  '/create_withManual': typeof Create_withManualRoute
  '/explore': typeof ExploreRoute
  '/explore_nearby_all': typeof Explore_nearby_allRoute
  '/explore_recommend_all': typeof Explore_recommend_allRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/personal-survey': typeof PersonalSurveyRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/trips': typeof TripsRoute
  '/admin/Test_Algorithm': typeof AdminTest_AlgorithmRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/place-images': typeof AdminPlaceImagesRoute
  '/admin/rating_attraction': typeof AdminRating_attractionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/trips_detail/$tripId': typeof Trips_detailTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/create_withAI': typeof Create_withAIRoute
  '/create_withManual': typeof Create_withManualRoute
  '/explore': typeof ExploreRoute
  '/explore_nearby_all': typeof Explore_nearby_allRoute
  '/explore_recommend_all': typeof Explore_recommend_allRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/personal-survey': typeof PersonalSurveyRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/trips': typeof TripsRoute
  '/admin/Test_Algorithm': typeof AdminTest_AlgorithmRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/place-images': typeof AdminPlaceImagesRoute
  '/admin/rating_attraction': typeof AdminRating_attractionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/trips_detail/$tripId': typeof Trips_detailTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/create_withAI'
    | '/create_withManual'
    | '/explore'
    | '/explore_nearby_all'
    | '/explore_recommend_all'
    | '/home'
    | '/login'
    | '/personal-survey'
    | '/profile-setup'
    | '/register'
    | '/saved'
    | '/trips'
    | '/admin/Test_Algorithm'
    | '/admin/map'
    | '/admin/place-images'
    | '/admin/rating_attraction'
    | '/auth/callback'
    | '/trips_detail/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/create_withAI'
    | '/create_withManual'
    | '/explore'
    | '/explore_nearby_all'
    | '/explore_recommend_all'
    | '/home'
    | '/login'
    | '/personal-survey'
    | '/profile-setup'
    | '/register'
    | '/saved'
    | '/trips'
    | '/admin/Test_Algorithm'
    | '/admin/map'
    | '/admin/place-images'
    | '/admin/rating_attraction'
    | '/auth/callback'
    | '/trips_detail/$tripId'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/create_withAI'
    | '/create_withManual'
    | '/explore'
    | '/explore_nearby_all'
    | '/explore_recommend_all'
    | '/home'
    | '/login'
    | '/personal-survey'
    | '/profile-setup'
    | '/register'
    | '/saved'
    | '/trips'
    | '/admin/Test_Algorithm'
    | '/admin/map'
    | '/admin/place-images'
    | '/admin/rating_attraction'
    | '/auth/callback'
    | '/trips_detail/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  Create_withAIRoute: typeof Create_withAIRoute
  Create_withManualRoute: typeof Create_withManualRoute
  ExploreRoute: typeof ExploreRoute
  Explore_nearby_allRoute: typeof Explore_nearby_allRoute
  Explore_recommend_allRoute: typeof Explore_recommend_allRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PersonalSurveyRoute: typeof PersonalSurveyRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  RegisterRoute: typeof RegisterRoute
  SavedRoute: typeof SavedRoute
  TripsRoute: typeof TripsRoute
  AdminTest_AlgorithmRoute: typeof AdminTest_AlgorithmRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminPlaceImagesRoute: typeof AdminPlaceImagesRoute
  AdminRating_attractionRoute: typeof AdminRating_attractionRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  Trips_detailTripIdRoute: typeof Trips_detailTripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create_withAI': {
      id: '/create_withAI'
      path: '/create_withAI'
      fullPath: '/create_withAI'
      preLoaderRoute: typeof Create_withAIRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create_withManual': {
      id: '/create_withManual'
      path: '/create_withManual'
      fullPath: '/create_withManual'
      preLoaderRoute: typeof Create_withManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore_nearby_all': {
      id: '/explore_nearby_all'
      path: '/explore_nearby_all'
      fullPath: '/explore_nearby_all'
      preLoaderRoute: typeof Explore_nearby_allRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore_recommend_all': {
      id: '/explore_recommend_all'
      path: '/explore_recommend_all'
      fullPath: '/explore_recommend_all'
      preLoaderRoute: typeof Explore_recommend_allRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-survey': {
      id: '/personal-survey'
      path: '/personal-survey'
      fullPath: '/personal-survey'
      preLoaderRoute: typeof PersonalSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/Test_Algorithm': {
      id: '/admin/Test_Algorithm'
      path: '/admin/Test_Algorithm'
      fullPath: '/admin/Test_Algorithm'
      preLoaderRoute: typeof AdminTest_AlgorithmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/admin/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/place-images': {
      id: '/admin/place-images'
      path: '/admin/place-images'
      fullPath: '/admin/place-images'
      preLoaderRoute: typeof AdminPlaceImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rating_attraction': {
      id: '/admin/rating_attraction'
      path: '/admin/rating_attraction'
      fullPath: '/admin/rating_attraction'
      preLoaderRoute: typeof AdminRating_attractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips_detail/$tripId': {
      id: '/trips_detail/$tripId'
      path: '/trips_detail/$tripId'
      fullPath: '/trips_detail/$tripId'
      preLoaderRoute: typeof Trips_detailTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  Create_withAIRoute: Create_withAIRoute,
  Create_withManualRoute: Create_withManualRoute,
  ExploreRoute: ExploreRoute,
  Explore_nearby_allRoute: Explore_nearby_allRoute,
  Explore_recommend_allRoute: Explore_recommend_allRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PersonalSurveyRoute: PersonalSurveyRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  RegisterRoute: RegisterRoute,
  SavedRoute: SavedRoute,
  TripsRoute: TripsRoute,
  AdminTest_AlgorithmRoute: AdminTest_AlgorithmRoute,
  AdminMapRoute: AdminMapRoute,
  AdminPlaceImagesRoute: AdminPlaceImagesRoute,
  AdminRating_attractionRoute: AdminRating_attractionRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  Trips_detailTripIdRoute: Trips_detailTripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
