-- Adaptive recommendation feedback loop
-- Stores explicit ratings, behavioral events, and learned 22D preference vectors.

create table if not exists public.user_place_feedback (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null,
  entity_type text not null
    check (entity_type in ('attraction', 'restaurant', 'accommodation')),
  entity_id text not null,
  rating smallint not null
    check (rating between 1 and 4),
  liked boolean null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (profile_id, entity_type, entity_id)
);

create table if not exists public.user_place_events (
  id bigint generated by default as identity primary key,
  profile_id uuid not null,
  entity_type text not null
    check (entity_type in ('attraction', 'restaurant', 'accommodation')),
  entity_id text not null,
  event_type text not null
    check (
      event_type in (
        'detail_open',
        'detail_dwell',
        'image_view',
        'save',
        'unsave',
        'add_to_trip',
        'remove_from_trip',
        'rating'
      )
    ),
  event_value double precision not null default 1,
  dwell_ms integer null,
  topic_vector double precision[] null,
  created_at timestamptz not null default now()
);

create table if not exists public.user_learned_preferences (
  profile_id uuid primary key,
  behavior_vector double precision[] not null
    default array_fill(0::double precision, array[22]),
  explicit_vector double precision[] not null
    default array_fill(0::double precision, array[22]),
  interaction_count integer not null default 0,
  version integer not null default 0,
  updated_at timestamptz not null default now(),
  constraint user_learned_behavior_vector_size
    check (array_length(behavior_vector, 1) = 22),
  constraint user_learned_explicit_vector_size
    check (array_length(explicit_vector, 1) = 22)
);

create table if not exists public.user_restaurant_learned_preferences (
  profile_id uuid primary key,
  behavior_vector double precision[] not null
    default array_fill(0::double precision, array[18]),
  explicit_vector double precision[] not null
    default array_fill(0::double precision, array[18]),
  interaction_count integer not null default 0,
  version integer not null default 0,
  updated_at timestamptz not null default now(),
  constraint user_restaurant_behavior_vector_size
    check (array_length(behavior_vector, 1) = 18),
  constraint user_restaurant_explicit_vector_size
    check (array_length(explicit_vector, 1) = 18)
);

create index if not exists idx_user_place_events_profile_created
  on public.user_place_events (profile_id, created_at desc);

create index if not exists idx_user_place_events_entity
  on public.user_place_events (entity_type, entity_id);

create index if not exists idx_user_place_feedback_profile
  on public.user_place_feedback (profile_id);

alter table public.user_place_feedback enable row level security;
alter table public.user_place_events enable row level security;
alter table public.user_learned_preferences enable row level security;
alter table public.user_restaurant_learned_preferences enable row level security;

drop policy if exists "Users manage own place feedback"
  on public.user_place_feedback;

create policy "Users manage own place feedback"
  on public.user_place_feedback
  for all
  using (auth.uid() = profile_id)
  with check (auth.uid() = profile_id);

drop policy if exists "Users manage own place events"
  on public.user_place_events;

create policy "Users manage own place events"
  on public.user_place_events
  for all
  using (auth.uid() = profile_id)
  with check (auth.uid() = profile_id);

drop policy if exists "Users manage own learned preferences"
  on public.user_learned_preferences;

create policy "Users manage own learned preferences"
  on public.user_learned_preferences
  for all
  using (auth.uid() = profile_id)
  with check (auth.uid() = profile_id);


drop policy if exists "Users manage own restaurant learned preferences"
  on public.user_restaurant_learned_preferences;

create policy "Users manage own restaurant learned preferences"
  on public.user_restaurant_learned_preferences
  for all
  using (auth.uid() = profile_id)
  with check (auth.uid() = profile_id);
